[terminal]
[terminal.shell]
program = "/sbin/zsh"

# Alacritty Configuration (TOML)

# Font settings
[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 10

# Window settings
[window]
padding = { x = 10, y = 10 }
opacity = 0.8 # Transparency (0.0 - fully transparent, 1.0 - opaque)
decorations = "full"  # Options: full, none, transparent, buttonless


# Scrolling
[scrolling]
history = 10000
multiplier = 3


[general]
import = [
    "/home/souvikkun/.config/alacritty/Themes/themes/dark_pride.toml"
]
